### ISSUE TITLE
Having issues to understand the process

### ISSUE THREAD

**Issue by wossix** [zigbeer/zapp-cie#1]
I have installed zapp-cie via npm and created a new javascript file in iobroker - but receiving this issue:

23:01:56.438 | [error] | javascript.0 script.js.Skript1: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/node_modules/zapp-cie'
-- | -- | --
23:01:56.438 | [error] | javascript.0 at script.js.Skript1:1:14
23:01:56.438 | [error] | javascript.0 script.js.Skript1: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/node_modules/zigbee-shepherd'

**Comment by wossix** [comment]
update: the issue was the path; but now I receive this error msg:

TypeError: "baudrate" is an unknown option, did you mean "baudRate"?
    at new SerialPort (/opt/iobroker/node_modules/serialport/lib/serialport.js:121:11)
    at CcZnp.init (/opt/iobroker/node_modules/cc-znp/lib/ccznp.js:115:71)
    at Promise.post (/opt/iobroker/node_modules/q/q.js:1181:36)
    at Promise.promise.promiseDispatch (/opt/iobroker/node_modules/q/q.js:808:41)
    at /opt/iobroker/node_modules/q/q.js:1411:14
    at runSingle (/opt/iobroker/node_modules/q/q.js:137:13)
    at flush (/opt/iobroker/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)


changed:
zigbee-shepherd/lib/shepherd.js
:42 spCfg.options = opts.hasOwnProperty('sp') ? opts.sp : { baud**R**ate: 115200, rtscts: true };

**Comment by simenkid** [comment]
@wossix I think the problem is not from the zapp-cie.
